config/routes.rb
Rails.application.routes.draw do
  namespace :admin do

    get '/' => 'homes#index'

    resources :users, only: [:index, :show]

    resources :posts, only: [:index, :show]

    resources :categories, only: [:show]

  end

  namespace :user do

    get '/' => 'homes#index'

    get '/about' => 'homes#about', as: 'about'

    resources :users, only: [:show, :edit, :update, :destroy]

    resources :posts do
      resource :comments, only: [:create]
    end


    resources :categories, only: [:show]

  end

  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	belongs_to :category

	has_many :bookmarks, dependent: :destroy
	has_many :comments

	attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :bookmarks, dependent: :destroy
         has_many :comments

         attachment :user_image

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def show
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

	def index
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	
	def after_sign_in_path_for(resource)
	user_posts_path # ログイン後
	end

  	def after_sign_out_path_for(resource)
  	user_posts_path # ログアウト後
    end

    protected

    def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
end

app/controllers/user/categories_controller.rb
class User::CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		comment = current_user.comments.new(comment_params)
		comment.post_id = post.id
		if comment.save
			flash[:notice] = 'コメントしました！'
			redirect_to comment.post
		else
		end
 	end
 	
	private

	def comment_params
	 params.require(:comment).permit(:user_id, :post_id, :content)
	end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

	def index
		@categories = Category.all
	end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
	#before_action :authenticate_user!, only: [:new, :edit, :create]
    def new
  		@post = Post.new
  	end

  	def index
  		@posts = Post.all.order(created_at: :desc)
  	end

  	def show
  		@post = Post.find(params[:id])
      @category = @post.category
  		@comments = @post.comments
  		@comment = Comment.new
  		@user = @post.user
  	end

  	def edit
  		@post = Post.find(params[:id])
  	end

  	def create
  		@post = Post.new(post_params)
  		@post.user_id = current_user.id
  		if @post.save
  			redirect_to user_posts_path
  		else
  			render :new
  		end
  	end

  	def update
  		@post = Post.find(params[:id])
    	if  @post.update(post_params)
        	redirect_to user_post_path(params[:id])
    	else
      		render :edit
    	end
  	end

  	def destroy
  		post = Post.find(params[:id])
  		post.destroy
  		redirect_to user_posts_path
  	end

  	private

  	def post_params
  		params.require(:post).permit(:image, :title, :body, :hospital, :cost, :user_id, :category_id)
  	end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_user_path(@user.id)
	end

	def destroy
	end

	private

	def user_params
		params.require(:user).permit(:name, :introduction, :user_image)
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/categories_helper.rb
module User::CategoriesHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

app/views/user/categories/show.html.erb
<div class="category-show">

	<h1>#<%= @category.category_name %></h1>

	<div class="category-posts">
		<% @category.posts.each do |post| %>
		<%= link_to user_post_path(post.id) do %>
		<div class="image">
			<%= attachment_image_tag post, :image, format: 'jpeg', fallback:"no_post_image.png", size: '300x300'  %>
		</div>

		<div class="title">
			<%= post.title %>
		</div>

		<div class="date">
			<%= post.created_at.strftime('%Y/%m/%d')%>
		</div>

		<div class="post-name">
			<%= attachment_image_tag post.user, :user_image, format: 'jpeg', fallback:"no_image.png", size: '40x40' %>
			<%= post.user.name %>
		</div>

		<% end %>
		<% end %>

	</div>

</div>

app/views/user/homes/about.html.erb
<div class="about">
	<h1>Teethは歯列矯正の情報を共有するサイトです
	</h1>
</div>

app/views/user/homes/index.html.erb
<div class="main">
	<h1>メインページ</h1>

	<div class="category">
		<h2>カテゴリー</h2>
		<% @categories.each do |category| %>
		<%= link_to user_category_path(category.id) do%>
		<div class="category-name">
		#<%= category.category_name %>
		<% end %>
		<% end %>
	</div>
</div>

app/views/user/posts/edit.html.erb
<div class="post-edit">

	<h1>編集</h1>
	<%= form_for @post, :url => { :controller => :posts, :action => :update } do |f| %>

	<div class="form-group">

	<%= f.attachment_field :image, placeolder:'画像' %>

	<h3>タイトル</h3>
	<%= f.text_field :title, class: 'form-control' %>

	<h5>病院名</h5>
	<%= f.text_field :hospital, class: 'form-control' %>

	<h5>費用</h5>
		<%= f.text_field :cost, class: 'form-control' %>

	<h3>本文</h3>
	<%= f.text_area :body, class: 'form-control', rows:10 %>

	<h4>カテゴリー</h4>
	<%= f.collection_select :category_id, Category.all, :id, :category_name %>

	<h4><%= f.submit '保存', class: 'btn btn-info btn-block' %></h4>

	<% end %>

</div>

app/views/user/posts/index.html.erb
<div class="posts-index">
	<h1>ALL POST</h1>

	<% @posts.each do |post| %>

	<div class="image">
	<%= attachment_image_tag post, :image, format: 'jpeg', fallback:"no_post_image.png", size: '300x300'  %>
	</div>

	<div class="title">
		<%= post.title %>
	</div>

	<div class="date">
		<%= post.created_at.strftime('%Y/%m/%d')%>
	</div>

	<div class="more">
	<%= link_to "more▶︎", user_post_path(post.id) %>
	</div>

	<div class="post-name">By
		<%= attachment_image_tag post.user, :user_image, format: 'jpeg', fallback:"no_image.png", size: '40x40' %>
		<%= post.user.name%>
	</div>

	<% end %>
</div>

app/views/user/posts/new.html.erb
<div class="post-new">

  <h1>NEW POST</h1>

  <%= form_for @post, :url => { :controller => :posts, :action => :create } do |f| %>

  	<div class="form-group">
  		<%= f.attachment_field :image %>
  	</div>

	<div class="form-group">
		<h3>タイトル</h3>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<h5>病院名</h5>
		<%= f.text_field :hospital, class: 'form-control' %>
	</div>

	<div class="form-group">
		<h5>費用</h5>
		<%= f.text_field :cost, class: 'form-control' %>
	</div>

	<div class="form-group">
		<h3>本文</h3>
		<%= f.text_area :body, class: 'form-control', rows:10 %>
	</div>

	<div class="form-group">
		<h4>カテゴリー</h4>
		<%= f.collection_select :category_id, Category.all, :id, :category_name %>
	</div>
	<%= f.submit '投稿', class: 'btn btn-info btn-block' %>

	<% end %>
</div>

app/views/user/posts/show.html.erb
<section class="post-show">
	<h2>POST</h2>
	<%= attachment_image_tag @post, :image, :fill, format: 'jpeg', fallback:"no_post_image.png", size: '250x250' %>
	<h3>タイトル</h3>
	<p><%= @post.title %></p>

	<h3>病院名</h3>
	<p><%= @post.hospital %></p>

	<h3>費用</h3>
	<p><%= @post.cost %></p>

	<h3><%= @post.body %></h3>

	<div class="category-name">
		<%= link_to user_category_path(@category.id) do %>
	<h4>#<%= @post.category.category_name %></h4>
	<% end %>
	</div>

	<div class="date">
	<%= @post.created_at.strftime('%Y/%m/%d')%>
	</div>
	<div class="post-name">By
		<%= link_to user_user_path(@user.id) do %>
		<%= attachment_image_tag @post.user, :user_image, format: 'jpeg', fallback:"no_image.png", size: '40x40' %>
		<%= @post.user.name %>
		<% end %>
	</div>

	<% if @post.user == current_user %>
	<%= link_to "編集", edit_user_post_path(@post.id), class: "btn btn-outline-info" %> / <%= link_to "削除", user_post_path(@post.id), method: :delete, "data-confirm" => "削除しますか？", class: "btn btn-outline-info" %>
	<% end %>

	<%= form_for [@post, @comment], url: user_post_comments_path(@post) do |f| %>
	<%= f.text_field :content %>
	<%= f.submit "送信" %>
	<% end %>

	<ol>
		<% @post.comments.each do |comment| %>
		<li class="comment">
				<%= attachment_image_tag comment.user, :user_image, format: 'jpeg', fallback:"no_image.png", size: '20x20' %>
				<%= comment.user.name%>
				<%= comment.content %>
				<%= comment.created_at.strftime('%Y/%m/%d') %>
		</li>
		<% end %>
	</ol>
</section>

app/views/user/users/edit.html.erb
<h2>My Page</h2>
	<p>マイページ編集</p>


<div class="profile">
	<%= form_for @user, :url => { :controller => :users, :action => :update }  do |f| %>

	<div class="icon">
		<%= f.attachment_field :user_image, placeholder: "プロフィール画像" %>
	</div>

	<h3 class="profile-name">名前<br />
		<%= f.text_field :name, :size => "20x20"  %>
	</h3>

	<h3 class="introduction">自己紹介文<br />
		<%= f.text_field :introduction , :size => "50x50" %>
	</h3>

	<p>
		<%= f.submit "Update" %>
	</p>

	<% end %>
</div>

app/views/user/users/show.html.erb
	<h2>My Page</h2>

	<div class="profile">
		<div class="icon">
			<%= attachment_image_tag @user, :user_image, size: '100', format: 'jpeg', fallback:"no_image.png" %>
		</div>
		<h3 class="profile-name">
			<%= @user.name %>
		</h3>
		<h4 class="introduction">
			<%= @user.introduction %>
		</h4>
	</div>

	<% if @user.id == current_user.id %>
	<%= link_to "プロフィール編集", edit_user_user_path(@user) , class: "btn btn-info"%>
	<%= link_to "アカウント削除", edit_user_user_path(@user), class: "btn btn-info" %>
	<% end %>

	<div class="posts">
		<h2>ALL POSTS</h2>
		<% @user.posts.each do |post| %>
		<%= link_to user_post_path(post.id) do %>
		<div class="image">
			<%= attachment_image_tag post, :image, format: 'jpeg', fallback:"no_post_image.png", size: '200x200'  %>
		</div>
		<div class="title">
			<%= post.title %>
		</div>
		<div class="date">
			<%= post.created_at.strftime('%Y/%m/%d')%>
		</div>
		<% end %>
		<% end %>
	</div>