config/routes.rb
Rails.application.routes.draw do
  namespace :admin do

    get '/' => 'homes#index'

    resources :users, only: [:index, :show]

    resources :posts, only: [:index, :show]

    resources :categories, only: [:show]

  end

  namespace :user do

    get '/' => 'homes#index'

    get '/about' => 'homes#about', as: 'about'

    resources :users, only: [:show, :edit, :update, :destroy]

    resources :posts do
      resource :comments, only: [:create]
    end


    resources :categories, only: [:show]

  end

  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	belongs_to :category

	has_many :bookmarks, dependent: :destroy
	has_many :comments

	attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :bookmarks, dependent: :destroy
         has_many :comments

         attachment :user_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	
	def after_sign_in_path_for(resource)
	user_posts_path # ログイン後
	end

  	def after_sign_out_path_for(resource)
  	user_posts_path # ログアウト後
    end

    protected

    def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

	def index
		@categories = Category.all
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/categories_helper.rb
module User::CategoriesHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teeth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">Teeth</div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to 'HOME', user_path %></li>
                <li><%= link_to 'ABOUT', user_about_path %></li>
                <li><%= link_to 'ALL POST', user_posts_path %></li>
                <li><%= link_to 'NEW POST', new_user_post_path %></li>
                <li><%= link_to 'MY PAGE', user_user_path(current_user.id) %></li>
                <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'HOME', user_path %></li>
                <li><%= link_to 'ABOUT', user_about_path %></li>
                 <li><%= link_to 'ALL POST', user_posts_path %></li>
                <li><%= link_to 'SIGN UP', new_user_registration_path %></li>
                <li><%= link_to 'LOG IN', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>